### ISSUE TITLE
So this works but...

### ISSUE THREAD

**Issue by Gothalpaca** [Tagueo/icue-ambilight#19] opened 2020-12-15 15:18 UTC
Hey,
So I downloaded this, and It's the best/easiest one to use that I've found so far.
However, I have found that even though it says full screen capture and I can see my full screen in the preview, the lighting only reflects what is shown in the top and left portions of the screen.
Can this be fixed?
![unregistered](https://user-images.githubusercontent.com/76057067/102233603-5be4fb00-3ee8-11eb-996c-f51e3be11fa4.jpg)
I have Icue running as Ambilight doesnt run without it.
Cheers!

**Comment by Tagueo** [comment] 2020-12-19 16:42
Hi, this is caused by the way I map devices to the screen. I'm currently working on a way to allow the user to select which part of the screen a connected device displays, so this will likely solve your problem.
Could you tell me which corsair devices are you using, so I can give a more specific look at your issue ?

**Comment by Gothalpaca** [comment] 2020-12-19 23:20
Hey!

3 x Sp120 (elite) front (built into 4000x case with pro node), 1 sp120 pro at back, hydro H100i rgb plat cooler and the cx650f (attached to node)
As said, it shows the full screen on preview, which is weird.

Cheers dude!
Enjoy your xmas if I dont hear from you before then :)

-------- Original Message --------

**Comment by Gothalpaca** [comment] 2020-12-19 23:22
I forgot - 2x8 rgb pro vengeance ram. All components in white except the sp120s.

-------- Original Message --------

**Comment by Gothalpaca** [comment] 2020-12-19 23:31
Apologies - my brain isnt working right now, it's the lighting node CORE that comes with the 4000x not pro. Shouldn't make a difference but just in case!

-------- Original Message --------

**Comment by dkbutxlo** [comment] 2020-12-20 09:19
can confirm, somehow the right part of my keyboard (numpad) isnt considered at all. So basically specially in AC Valhalla 75% of the keyboard is flickering white and blue. Maybe there is a way to connect this whole thing with https://sabaatworld.github.io/HyperionScreenCap/ ?

**Comment by Tagueo** [comment] 2020-12-22 19:13
I have some news!
I found a reliable way to scale the coordinates of the devices and its working well!
The ux is still a bit rough so I'll improve it before putting it into a release.

Here is a sneak peak at how it actually looks :
- Before resizing :
![image](https://user-images.githubusercontent.com/33714922/102924528-0d100600-4492-11eb-93bc-642a89a28dce.png)

- After resizing the keyboard to fit the whole screen :
![image](https://user-images.githubusercontent.com/33714922/102924574-2749e400-4492-11eb-9a27-6acca66bcfd2.png)

**Comment by Tagueo** [comment] 2021-01-03 11:16
Hi ! The feature has now been implemented in the app and is present in the last release, I'm therefore closing this issue, if you have any problems/suggestions with this new feature feel free to open a new one!

**Closed by Tagueo** 2021-01-03 11:16 UTC
Labels: enhancement
