### ISSUE TITLE
Device with no LEDs on it cause an error when retrieving the positions

### ISSUE THREAD

**Issue by KhnifesKyrillus** [Tagueo/icue-ambilight#18] opened 2020-12-14 22:35 UTC
Hello,
I have installed the ambilight program and started it. Everything looks fine but the problem is it doesn't work my lights don't change.

These are the errors I get:
![Screenshot 2020-12-14 233856](https://user-images.githubusercontent.com/43353117/102144349-9ce7fb80-3e65-11eb-8664-66deca910a57.png)

**Comment by Tagueo** [comment] 2020-12-19 17:06
Hi, could you retry the software with the last version ?
Also please go in the settings section and post a screenshot of which devices are currently connected.
Thanks in advance 😄

**Comment by KhnifesKyrillus** [comment] 2020-12-21 22:40
![Screenshot 2020-12-21 233929](https://user-images.githubusercontent.com/43353117/102828758-cbc21c80-43e5-11eb-91f9-c46d4aaad520.png)
Hey,
I downloaded the latest version and it still doesn't work.

Thanks for the help

**Comment by Tagueo** [comment] 2020-12-22 19:18
Thanks, I may have an idea of the cause of the bug, but I will have to do some testing.
I think this is caused by your HS70 Pro Wireless since I'm trying to find the postion of the leds on it and it hasn't any.
I will get back to you when I'll be confident the bug is fixed.
Thanks again!

**Comment by KhnifesKyrillus** [comment] 2020-12-23 14:05
Yeah you are right I tried it without my headset plugged in and it works.
Thanks for the help

**Comment by Tagueo** [comment] 2020-12-23 17:56
Thanks for trying, now I'm 100% sure that's the cause of the bug.
I'll get back to you when this will be fixed 😄

**Comment by rbcetin** [comment] 2020-12-31 12:15
An option for disabling specific devices would be good also. I am dependent on demo devices to use JackNet so there are some demo devices activated in iCUE but not in use.

**Comment by horbiger** [comment] 2021-01-06 17:52
Bonjour , deja merci pour ce super logiciel ambilight ! 
j 'ai téléchargé la dernier version 1.4.0 et elle ne fonctionne pas pour ma part. la version1.3.0 fonctionnait pourtant, avec les problème évoquer. l'histoire de la zone gauche et haute    
Sur la dernière version , je ne peux accéder à aucun onglet . Quand je lance le logiciel il ne bascule pas en mode ambilight contrairement à la 1.3.0 .  bon courage ;-)

**Comment by Tagueo** [comment] 2021-01-06 18:14
> Bonjour , deja merci pour ce super logiciel ambilight !
> j 'ai téléchargé la dernier version 1.4.0 et elle ne fonctionne pas pour ma part. la version1.3.0 fonctionnait pourtant, avec les problème évoquer. l'histoire de la zone gauche et haute
> Sur la dernière version , je ne peux accéder à aucun onglet . Quand je lance le logiciel il ne bascule pas en mode ambilight contrairement à la 1.3.0 . bon courage ;-)

Bonjour, merci d'ouvrir une nouvelle issue avec tout les détails demandés pour m'aider a resoudre le problème 😉

**Comment by Tagueo** [comment] 2021-01-25 09:23
Hi again, thanks for your additional feedback.
I've pushed a release that *should* have fixed the problem.
Once again, I have no device able to reproduce this issue so I'm not sure that this will work.
I'll close the related issues when I'll be sure this is fixed!

**Comment by KhnifesKyrillus** [comment] 2021-01-25 14:43
@Tagueo I can use the software now but the led don't change their color so I assume it doesn't work

**Comment by KhnifesKyrillus** [comment] 2021-01-25 14:48
I think the issue is fixed. Thank you

**Comment by KhnifesKyrillus** [comment] 2021-01-25 17:39
After some testing I have found a problem.
The software just works if the device with no leds is disconnected at the first start after the first start  it works fine.

**Comment by Tagueo** [comment] 2021-01-28 05:52
Could you repost the new error log if there is one ? Thanks in advance

**Comment by KhnifesKyrillus** [comment] 2021-01-30 14:20
![Screenshot 2021-01-30 151947](https://user-images.githubusercontent.com/43353117/106358788-9ecf2680-630e-11eb-81f6-92f5900d6c54.png)

**Closed** 2021-03-05 15:59 UTC
Labels: bug
